# File managed by pluginsync
sudo: true
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Oaadz1WqX1oRyDh/03JPeCup0DbQ3972PRBgVwkFP1eW7oh+RbGdTTnADskH9h6ebov1eBZejOtZqu2Puy/JIiGbfQ2wBg0ONnlwgFCDndG6tsOB8M95jKKp4XDVJQ6Z2sPJbMVOz+JSsnYpcB8+LpYTu3dUP6nKIM9vherAiN+ORmfdK4s1q51H91+5HWB8ugHgFXFadhsce4H/k8NWQ/XREnPFG5kho6iQ7Slf3XZvDD3vik4/snaOi22b6+cK7ez8QtRS4C7sroD2U/nrZuNR91hkC/dWbHR1Nv2wobjbW6yXGcE+jcHU+rh/yWfOO1BHACfTmdYm2G+ROCXmlXVFB4BLBNy5BseDBGV4Iu1JLGL1tgr3EbDGi45IC9rxUk0Xw09QMUBEcjSmI8KpGmXYz6XCBPAw0ZHhWfokDPBPGgvv5fLp+QiCn877DkgsLdVaz0caAVhk8r70301CGneEg9VPtoBkHMQpUPwEW623hEKEy/uAP2BWyhZTM0NivmVX9R/op1MaFzCuMdc699nxT4GyhqywzBP2z1d7eonn9JTHwYtOf4Y0RKFjSJ+B7W6E41xtjvf6dyrq+22Oqx+yeiI5RvONLW9f5NlKxZ8xJ+aWnfNTd8DZomqxWGgii6clQXQsu/+87Y3EW1Mz/3rlmIZ1iCug2P2fJ3P8VAg=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-processes
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Oaadz1WqX1oRyDh/03JPeCup0DbQ3972PRBgVwkFP1eW7oh+RbGdTTnADskH9h6ebov1eBZejOtZqu2Puy/JIiGbfQ2wBg0ONnlwgFCDndG6tsOB8M95jKKp4XDVJQ6Z2sPJbMVOz+JSsnYpcB8+LpYTu3dUP6nKIM9vherAiN+ORmfdK4s1q51H91+5HWB8ugHgFXFadhsce4H/k8NWQ/XREnPFG5kho6iQ7Slf3XZvDD3vik4/snaOi22b6+cK7ez8QtRS4C7sroD2U/nrZuNR91hkC/dWbHR1Nv2wobjbW6yXGcE+jcHU+rh/yWfOO1BHACfTmdYm2G+ROCXmlXVFB4BLBNy5BseDBGV4Iu1JLGL1tgr3EbDGi45IC9rxUk0Xw09QMUBEcjSmI8KpGmXYz6XCBPAw0ZHhWfokDPBPGgvv5fLp+QiCn877DkgsLdVaz0caAVhk8r70301CGneEg9VPtoBkHMQpUPwEW623hEKEy/uAP2BWyhZTM0NivmVX9R/op1MaFzCuMdc699nxT4GyhqywzBP2z1d7eonn9JTHwYtOf4Y0RKFjSJ+B7W6E41xtjvf6dyrq+22Oqx+yeiI5RvONLW9f5NlKxZ8xJ+aWnfNTd8DZomqxWGgii6clQXQsu/+87Y3EW1Mz/3rlmIZ1iCug2P2fJ3P8VAg=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-processes
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: SE6vXR6+9xQscO6sZ5VRfsYI792WOs4ReqZAC8dufExu1RqJI/zYkRmK5gTL/Q95qMgcnepthotLBXKWQYw7ymPiG+pAB4qvttU75RH2+7G3Nj3TGR5iqt5BBEAY2gqQmoC8jGKb5Wu7TvpNS8qU7oia8Mta0LPIstUQHwyfMzZGhIxpC09w+HMKfZNTSrYgVQKvncOfDE2QMCqrDdFdl2FkOw6pTGsgVRvFVEeYEVROVu98/0WqVNc7R4/va4N76cj5Yni2uIlcQIMDuIpbl7Pw7f2woTInw4qzeMN3+itydUXXYC72somo1UmJ9YPLpPGkIbSF2TvDvMoD2OsVGtAllr1V9akxeIaJRGGSveiYyuv+LNZzkdBVAovrplw8N+QPazYvcJeWsvz1H107TMvnYrmfBVjQ+eUh6S5QxTymMBA0ureMlqnpbM9B7MursqXgL0XeemoCIBadFtA/K17sIj3LvKNBfQrSGsyJ7LAMDm8+ZnEhxfSQQmgvfhek/JJW9f6Qn1BTdaPXHl9pIyccOd3FEhmVjCn2Tyv8dJmRpDSPeVhuLzIZoDz0KZfEAMuegV4zBfhQEYxz/YqkVL2/vx5E38G4ZRRJxJh5tCOIXLNdsssd65oNGP2bjiQO2nADgWBmg6o+Nk4MEqhdYH6/1Y9U5llpUwQVfHe2YR4=
  file:
    - release/snap-plugin-collector-processes_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-processes
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
